"""Quitar subject (HOTFIX)

Revision ID: ed1285a5d8fb
Revises: cf0b25cd38da
Create Date: 2025-11-14 02:00:11.896913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed1285a5d8fb'
down_revision = 'cf0b25cd38da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
